#!/bin/sh

# TODO: Expand the Docker image

systemctl enable statuspanel-service.service
systemctl start statuspanel-service.service

docker load < /usr/share/statuspanel-service/statuspanel-web-latest.tar.gz
