#!/bin/sh

# Load the Docker image.
docker load < /usr/share/statuspanel-service/statuspanel-web-latest.tar.gz

# Enable and start the service.
systemctl enable statuspanel-service.service
systemctl start statuspanel-service.service
