version: '3.8'
name: statuspanel

services:
  web:
    image: $IMAGE_SHA
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://hello_flask:hello_flask@database:5432/hello_flask_dev
      - APNS_TEAM_ID
      - APNS_BUNDLE_ID
      - APNS_KEY_ID
      - APNS_KEY
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    volumes:
      - statuspanel_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - 54320:5432


volumes:
  statuspanel_data:
