version: '3.8'
name: statuspanel

services:
  web:
    build: web
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://hello_flask:hello_flask@database:5432/hello_flask_dev
      - APNS_TEAM_ID
      - APNS_BUNDLE_ID
      - ANPS_KEY_ID
      - APNS_KEY
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
