- name: statuspanel.io
  hosts: inseven

  # As of right now, the server uses ufw for firewall management.
  # sudo ufw allow 443

  tasks:

    - name: Install dependencies
      apt:
        pkg:
          - python3-certbot
          - python3-certbot-nginx
      become: yes

    - name: Create destination directory
      file:
        path: /opt/statuspanel
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      become: yes

    - name: Synchronize files
      synchronize:
        src: "{{ playbook_dir }}/../build/"
        dest: /opt/statuspanel/
        delete: yes

    - name: Stop service
      systemd:
        state: stopped
        name: statuspanel.service
      become: yes

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/statuspanel.conf
        dest: /etc/nginx/sites-enabled/statuspanel.conf
        owner: root
        group: root
        state: link
      become: yes

    - name: Register certbot
      shell: |
        /usr/bin/certbot -n register --agree-tos --email webmaster@inseven.co.uk
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered
      become: yes

    - name: Create certificate
      command: '/usr/bin/certbot -n --nginx certonly -d staging.statuspanel.io'
      args:
        creates: '/etc/letsencrypt/live/staging.statuspanel.io'
      ignore_errors: true
      become: true

    - name: Start service
      systemd:
        state: started
        name: statuspanel.service
        daemon_reload: yes
      become: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
