- name: statuspanel.io
  hosts: all

  tasks:

    - name: Copy Debian package
      copy:
        src: "{{ package_path }}"
        dest: /tmp/statuspanel-service.deb

    - name: Create environment file
      template:
        src: templates/env
        dest: /usr/share/statuspanel-service/.env
      become: yes

    - name: Install the service
      apt:
        deb: /tmp/statuspanel-service.deb
      become: yes

    - name: Enable site
      file:
        src: templates/site.caddy
        dest: "/etc/caddy/statuspanel.caddy"
        owner: root
        group: root
        state: link
      become: yes

    - name: Reload Caddy
      service:
        name: caddy
        state: reloaded
      become: yes
