#!/bin/bash

# Copyright (c) 2018-2022 Jason Morley, Tom Sutcliffe
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

SCRIPTS_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIRECTORY="${SCRIPTS_DIRECTORY}/.."

JWT_PRIVATE_KEY_PATH="${ROOT_DIRECTORY}/apns.p8"
JWT_PRIVATE_KEY=`cat "${JWT_PRIVATE_KEY_PATH}"`

APNS_TEAM_ID=S4WXAUZQEV
APNS_BUNDLE_ID=uk.co.inseven.status-panel
ANPS_KEY_ID=V5XKL2D8B9
APNS_KEY=$JWT_PRIVATE_KEY

heroku buildpacks:clear --app $1
heroku buildpacks:set heroku/python --app $1

heroku config:set "JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY" --app $1
heroku config:set "APNS_TEAM_ID=$APNS_TEAM_ID" --app $1
heroku config:set "APNS_BUNDLE_ID=$APNS_BUNDLE_ID" --app $1
heroku config:set "ANPS_KEY_ID=$ANPS_KEY_ID" --app $1
heroku config:set "APNS_KEY=$APNS_KEY" --app $1
