name: build-raspberry-pi-image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build-raspberry-pi-image:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy Python source
      run: |
        cp -R device/python/src device/python/raspberry-pi-image/00-install-statuspanel/files

    - name: Build image
      id: build
      uses: usimd/pi-gen-action@v1
      with:
        image-name: statuspanel
        hostname: statuspanel
        stage-list: stage0 stage1 stage2 device/python/raspberry-pi-image
        pi-gen-version: bullseye-arm64
        verbose-output: true

    - uses: actions/upload-artifact@v3
      with:
        name: pi-gen-image
        path: ${{ steps.build.outputs.image-path }}
