name: build-firmware

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build-firmware:

    name: build-firmware
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache build directory
      id: cache-build
      uses: actions/cache@v3
      with:
        path: device/nodemcu/nodemcu-firmware/build
        key: ${{ runner.os }}-build

    - name: Build
      run: |
        device/nodemcu/build.sh

    - name: Archive the firmware
      uses: actions/upload-artifact@v2
      with:
        path: device/nodemcu/build/firmware-esp32.zip
        if-no-files-found: error
