name: build-service

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test-service:

    name: build-service
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout required submodules
      run: |
        git submodule update --init --depth 1 scripts/build-tools

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build and test
      env:
        BUILD_PACKAGE: true
      run: |
        scripts/build-service.sh

    - name: Purge all Docker images
      run: |
        docker system prune --all --force
        docker image prune --all --force
        docker container ls
        docker image ls

    - name: Archive the Debian package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: service/build/statuspanel-service-*.deb
        if-no-files-found: error

    - name: Install and test the package
      run: |
        sudo mkdir -p /usr/share/statuspanel-service/
        echo SKIP_APNS_STARTUP_CHECK=true | sudo tee -a /usr/share/statuspanel-service/.env
        sudo apt-get install ./service/build/statuspanel-service-*.deb
        sleep 5
        sudo systemctl status statuspanel-service.service
        journalctl -u statuspanel-service.service
        scripts/test-service.sh

    - name: Deploy the service
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
        ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      run: |
        service/ansible/deploy.sh service/build/statuspanel-service-*.deb
