name: pi-gen

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build:

    # strategy:
    #   matrix:
    #     include:
    #       - pi-gen-version: bullseye-arm64
    #         release: bullseye
    #       - pi-gen-version: bullseye
    #         release: bullseye
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: |
        scripts/build-raspberry-pi-image.sh

    # - name: Archive the image
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: pi-gen-image
    #     path: ${{ steps.build.outputs.image-path }}
    #     if-no-files-found: error
