name: test-service

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test-service:

    name: test-service
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout required submodules
      run: |
        git submodule update --init --depth 1 scripts/build-tools

    - name: Show the version of Docker
      run: |
        sudo apt search docker

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build and test
      env:
        APNS_TEAM_ID: ${{ secrets.APNS_TEAM_ID }}
        APNS_BUNDLE_ID: ${{ secrets.APNS_BUNDLE_ID }}
        ANPS_KEY_ID: ${{ secrets.ANPS_KEY_ID }}
        APNS_KEY: ${{ secrets.APNS_KEY }}
      run: |
        scripts/build-service.sh

    - name: Install the package for testing
      run: |
        sudo apt-get install ./service/build/statuspanel-service-*.deb docker-ce-

    - name: Archive the Debian package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: service/build/statuspanel-service-*.deb
        if-no-files-found: error
